$iconMap = @{
    'add' = 'plus'
    'add_circle' = 'circlePlus'
    'add_location_alt' = 'locationDot'
    'add_photo_alternate' = 'image'
    'admin_panel_settings' = 'userShield'
    'alarm' = 'regularBell'
    'alternate_email' = 'at'
    'analytics' = 'chartLine'
    'archive' = 'fileArchive'
    'arrow_back' = 'arrowLeft'
    'arrow_back_ios_new' = 'chevronLeft'
    'arrow_forward' = 'arrowRight'
    'arrow_forward_ios' = 'chevronRight'
    'arrow_outward' = 'arrowUpRightFromSquare'
    'assignment_ind' = 'addressCard'
    'assignment' = 'regularFileLines'
    'assignment_turned_in' = 'fileCircleCheck'
    'attach_file' = 'paperclip'
    'attach_money' = 'dollarSign'
    'autorenew' = 'arrowsRotate'
    'badge' = 'idBadge'
    'calendar_month' = 'regularCalendar'
    'calendar_today' = 'regularCalendar'
    'call_end' = 'phoneSlash'
    'call' = 'phone'
    'camera_alt' = 'camera'
    'cancel' = 'circleXmark'
    'category' = 'list'
    'chat_bubble_outline' = 'regularComment'
    'chat_bubble' = 'comment'
    'check_box_outline_blank' = 'regularSquare'
    'check_box' = 'squareCheck'
    'check_circle_outline' = 'regularCircleCheck'
    'check_circle' = 'circleCheck'
    'check' = 'check'
    'chevron_left' = 'chevronLeft'
    'chevron_right' = 'chevronRight'
    'cleaning_services' = 'broom'
    'close' = 'xmark'
    'collections_bookmark' = 'bookmark'
    'comment' = 'regularComment'
    'content_copy' = 'copy'
    'credit_card' = 'creditCard'
    'dashboard' = 'chartPie'
    'date_range' = 'regularCalendar'
    'delete_forever' = 'trashCan'
    'delete_outline' = 'regularTrashCan'
    'delete' = 'trashCan'
    'description' = 'regularFileLines'
    'directions' = 'directions'
    'done_all' = 'checkDouble'
    'done' = 'check'
    'edit_calendar' = 'calendarPen'
    'edit_note' = 'penToSquare'
    'edit' = 'penToSquare'
    'email' = 'regularEnvelope'
    'error_outline' = 'circleExclamation'
    'error' = 'circleExclamation'
    'event_available' = 'calendarCheck'
    'event_note' = 'regularCalendar'
    'event' = 'calendar'
    'exit_to_app' = 'rightFromBracket'
    'expand_more' = 'chevronDown'
    'explore' = 'compass'
    'favorite_border' = 'regularHeart'
    'favorite' = 'heart'
    'file_copy' = 'copy'
    'file_download' = 'download'
    'file_present' = 'file'
    'filter_list' = 'filter'
    'fingerprint' = 'fingerprint'
    'flag' = 'flag'
    'grid_view' = 'tableCells'
    'groups' = 'users'
    'help_outline' = 'regularCircleQuestion'
    'history' = 'clockRotateLeft'
    'home' = 'house'
    'image_not_supported' = 'image'
    'image' = 'regularImage'
    'info_outline' = 'regularCircleInfo'
    'info' = 'circleInfo'
    'keyboard_arrow_down' = 'chevronDown'
    'keyboard_arrow_right' = 'chevronRight'
    'keyboard_arrow_up' = 'chevronUp'
    'language' = 'globe'
    'layers' = 'layerGroup'
    'leaderboard' = 'chartSimple'
    'lightbulb_outline' = 'regularLightbulb'
    'list_alt' = 'listUl'
    'local_hospital' = 'plus'
    'local_offer' = 'tag'
    'local_shipping' = 'truck'
    'location_on' = 'locationDot'
    'lock_clock' = 'lock'
    'lock_open' = 'lockOpen'
    'lock_outline' = 'lock'
    'lock_reset' = 'lock'
    'lock' = 'lock'
    'login' = 'rightToBracket'
    'logout' = 'rightFromBracket'
    'mail_outline' = 'regularEnvelope'
    'mail' = 'envelope'
    'map' = 'regularMap'
    'menu_open' = 'bars'
    'menu' = 'bars'
    'message' = 'regularComment'
    'mic_none' = 'microphoneSlash'
    'mic' = 'microphone'
    'more_horiz' = 'ellipsis'
    'more_vert' = 'ellipsisVertical'
    'my_location' = 'locationCrosshairs'
    'notifications_active' = 'regularBell'
    'notifications_none' = 'regularBell'
    'notifications' = 'regularBell'
    'open_in_new' = 'arrowUpRightFromSquare'
    'payment' = 'creditCard'
    'pending_actions' = 'clock'
    'pending' = 'ellipsis'
    'people_alt' = 'users'
    'people' = 'users'
    'perm_identity' = 'regularUser'
    'person_add_alt_1' = 'userPlus'
    'person_outline' = 'regularUser'
    'person' = 'user'
    'person_search' = 'user'
    'phone_android' = 'mobile'
    'phone_iphone' = 'mobile'
    'phone' = 'phone'
    'photo_camera_back' = 'camera'
    'photo_camera' = 'camera'
    'photo_library' = 'images'
    'photo' = 'regularImage'
    'place' = 'locationDot'
    'play_arrow' = 'play'
    'play_circle_outline' = 'regularCirclePlay'
    'query_builder' = 'clock'
    'question_answer' = 'comments'
    'radio_button_checked' = 'circleDot'
    'radio_button_unchecked' = 'regularCircle'
    'receipt_long' = 'fileInvoice'
    'receipt' = 'fileInvoice'
    'redeem' = 'gift'
    'remove_circle_outline' = 'regularCircleMinus'
    'remove_red_eye' = 'regularEye'
    'report_problem' = 'triangleExclamation'
    'reviews' = 'regularStar'
    'save' = 'regularFloppyDisk'
    'schedule' = 'regularCalendar'
    'school' = 'graduationCap'
    'search' = 'magnifyingGlass'
    'send' = 'paperPlane'
    'settings' = 'gear'
    'shield' = 'shield'
    'star_border' = 'regularStar'
    'star' = 'star'
    'timer' = 'clock'
    'verified_user' = 'userShield'
    'videocam' = 'video'
    'visibility_off' = 'regularEyeSlash'
    'visibility' = 'regularEye'
    'warning_amber' = 'triangleExclamation'
    'warning' = 'triangleExclamation'
    'refresh' = 'rotateRight'
    'call_received' = 'arrowDown'
    'call_made' = 'arrowUp'
    'videocam_off' = 'videoSlash'
    'star_half' = 'starHalfStroke'
    'share' = 'shareNodes'
    'remove' = 'minus'
    'work_outline' = 'regularBriefcase'
    'work' = 'briefcase'
    'search_off' = 'magnifyingGlass'
    'translate' = 'language'
    'switch_camera' = 'cameraRotate'
    'swap_horiz' = 'rightLeft'
    'subscriptions' = 'video'
    'shopping_cart' = 'cartShopping'
}

$files = Get-ChildItem -Path lib -Filter *.dart -Recurse
foreach ($file in $files) {
    if ($file.Length -eq 0) { continue }
    $content = Get-Content $file.FullName -Raw
    if ($null -eq $content) { continue }
    $modified = $false
    
    foreach ($key in $iconMap.Keys) {
        $faName = $iconMap[$key]
        # Match Icons.name optionally followed by _rounded, _outlined, or _sharp
        # Use regex boundary that accounts for underscores
        $pattern = "\bIcons\." + $key + "(_rounded|_outlined|_sharp)?\b"
        
        if ($content -match $pattern) {
            $content = $content -replace $pattern, "FontAwesomeIcons.$faName"
            $modified = $true
        }
    }
    
    if ($modified) {
        # Convert Icon(...) to FaIcon(...)
        $content = $content -replace "Icon\(FontAwesomeIcons\.", "FaIcon(FontAwesomeIcons."
        
        # Add import if missing
        if ($content -notmatch "import 'package:font_awesome_flutter/font_awesome_flutter.dart';") {
            # Find the first import and prepend to it
            if ($content -match "import '") {
                $content = $content -replace "import '", "import 'package:font_awesome_flutter/font_awesome_flutter.dart';`nimport '"
            } else {
                $content = "import 'package:font_awesome_flutter/font_awesome_flutter.dart';`n" + $content
            }
        }
        
        Set-Content -Path $file.FullName -Value $content -Encoding UTF8
    }
}
