$iconMap = @{
    'access_time' = 'clock'
    'access_time_filled' = 'clock'
    'account_balance' = 'buildingColumns'
    'account_balance_wallet' = 'wallet'
    'add' = 'plus'
    'add_a_photo' = 'camera'
    'add_business' = 'buildingCircleCheck'
    'add_circle' = 'circlePlus'
    'add_circle_outline' = 'circlePlus'
    'add_location_alt' = 'locationDot'
    'add_photo_alternate' = 'regularImage'
    'add_to_drive' = 'hardDrive'
    'admin_panel_settings' = 'userShield'
    'alarm' = 'regularBell'
    'alternate_email' = 'at'
    'analytics' = 'chartLine'
    'apple' = 'apple'
    'archive' = 'fileArchive'
    'arrow_back' = 'arrowLeft'
    'arrow_back_ios_new' = 'chevronLeft'
    'arrow_drop_down' = 'chevronDown'
    'arrow_forward' = 'arrowRight'
    'arrow_forward_ios' = 'chevronRight'
    'arrow_outward' = 'arrowUpRightFromSquare'
    'assignment_ind' = 'addressCard'
    'assignment' = 'regularFileLines'
    'assignment_turned_in' = 'fileCircleCheck'
    'attach_file' = 'paperclip'
    'attach_money' = 'dollarSign'
    'auto_awesome' = 'wandMagicSparkles'
    'autorenew' = 'arrowsRotate'
    'badge' = 'idBadge'
    'block' = 'ban'
    'bolt' = 'bolt'
    'broken_image' = 'imageSlash'
    'build' = 'wrench'
    'business_center' = 'briefcase'
    'business' = 'building'
    'cake' = 'cakeCandles'
    'calendar_month' = 'regularCalendar'
    'calendar_today' = 'regularCalendar'
    'call_end' = 'phoneSlash'
    'call' = 'phone'
    'camera_alt' = 'camera'
    'cancel' = 'circleXmark'
    'category' = 'list'
    'chat_bubble_outline' = 'regularComment'
    'chat_bubble' = 'comment'
    'check_box_outline_blank' = 'regularSquare'
    'check_box' = 'squareCheck'
    'check_circle_outline' = 'regularCircleCheck'
    'check_circle' = 'circleCheck'
    'check' = 'check'
    'chevron_left' = 'chevronLeft'
    'chevron_right' = 'chevronRight'
    'cleaning_services' = 'broom'
    'close' = 'xmark'
    'cloud_upload' = 'cloudArrowUp'
    'collections' = 'images'
    'collections_bookmark' = 'bookmark'
    'comment' = 'regularComment'
    'content_copy' = 'copy'
    'credit_card' = 'creditCard'
    'dark_mode' = 'moon'
    'dashboard' = 'chartPie'
    'date_range' = 'regularCalendar'
    'delete_forever' = 'trashCan'
    'delete_outline' = 'regularTrashCan'
    'delete' = 'trashCan'
    'delivery_dining' = 'motorcycle'
    'description' = 'regularFileLines'
    'directions' = 'directions'
    'done_all' = 'checkDouble'
    'done' = 'check'
    'edit_calendar' = 'calendarDay'
    'edit_document' = 'penToSquare'
    'edit_note' = 'penToSquare'
    'edit' = 'penToSquare'
    'electrical_services' = 'plug'
    'email' = 'regularEnvelope'
    'engineering' = 'helmetSafety'
    'error_outline' = 'circleExclamation'
    'error' = 'circleExclamation'
    'event_available' = 'calendarCheck'
    'event_note' = 'regularCalendar'
    'event' = 'calendar'
    'exit_to_app' = 'rightFromBracket'
    'expand_more' = 'chevronDown'
    'explore' = 'compass'
    'favorite_border' = 'regularHeart'
    'favorite_outline' = 'regularHeart'
    'favorite' = 'heart'
    'file_copy' = 'copy'
    'file_download' = 'download'
    'file_present' = 'file'
    'filter_list' = 'filter'
    'fingerprint' = 'fingerprint'
    'flag' = 'flag'
    'gavel' = 'gavel'
    'grid_view' = 'tableCells'
    'groups' = 'users'
    'handshake' = 'handshake'
    'handyman' = 'hammer'
    'help_outline' = 'regularCircleQuestion'
    'history' = 'clockRotateLeft'
    'home_repair_service' = 'toolbox'
    'home' = 'house'
    'hourglass_empty' = 'hourglass'
    'image_not_supported' = 'imageSlash'
    'image' = 'regularImage'
    'info_outline' = 'regularCircleInfo'
    'info' = 'circleInfo'
    'inventory_2' = 'boxOpen'
    'keyboard_arrow_down' = 'chevronDown'
    'keyboard_arrow_right' = 'chevronRight'
    'keyboard_arrow_up' = 'chevronUp'
    'key' = 'key'
    'label_outline' = 'regularTag'
    'language' = 'globe'
    'layers' = 'layerGroup'
    'leaderboard' = 'chartSimple'
    'lightbulb_outline' = 'regularLightbulb'
    'list_alt' = 'listUl'
    'local_hospital' = 'plus'
    'local_offer' = 'tag'
    'local_shipping' = 'truck'
    'location_city' = 'buildingCity'
    'location_on' = 'locationDot'
    'location_searching' = 'locationCrosshairs'
    'lock_clock' = 'lock'
    'lock_open' = 'lockOpen'
    'lock_outline' = 'lock'
    'lock_reset' = 'lock'
    'lock' = 'lock'
    'login' = 'rightToBracket'
    'logout' = 'rightFromBracket'
    'mail_outline' = 'regularEnvelope'
    'mail' = 'envelope'
    'map' = 'regularMap'
    'mark_email_read' = 'envelopeCircleCheck'
    'menu_open' = 'bars'
    'menu' = 'bars'
    'message' = 'regularComment'
    'mic_none' = 'microphoneSlash'
    'mic_off' = 'microphoneSlash'
    'mic' = 'microphone'
    'military_tech' = 'medal'
    'more_horiz' = 'ellipsis'
    'more_vert' = 'ellipsisVertical'
    'my_location' = 'locationCrosshairs'
    'navigation' = 'compass'
    'near_me' = 'locationArrow'
    'new_releases' = 'certificate'
    'notes' = 'noteSticky'
    'notifications_active' = 'regularBell'
    'notifications_none' = 'regularBell'
    'notifications_off' = 'regularBellSlash'
    'notifications' = 'regularBell'
    'open_in_new' = 'arrowUpRightFromSquare'
    'password' = 'asterisk'
    'payment' = 'creditCard'
    'payments' = 'creditCard'
    'pending_actions' = 'clock'
    'pending' = 'ellipsis'
    'people_alt' = 'users'
    'people_outline' = 'users'
    'people' = 'users'
    'perm_identity' = 'regularUser'
    'person_add_alt_1' = 'userPlus'
    'person_outline' = 'regularUser'
    'person' = 'user'
    'person_search' = 'user'
    'phone_android' = 'mobile'
    'phone_iphone' = 'mobile'
    'phone' = 'phone'
    'photo_camera_back' = 'camera'
    'photo_camera' = 'camera'
    'photo_library' = 'images'
    'photo' = 'regularImage'
    'pin_drop' = 'mapPin'
    'pin' = 'thumbtack'
    'place' = 'locationDot'
    'play_arrow' = 'play'
    'play_circle_outline' = 'regularCirclePlay'
    'plumbing' = 'wrench'
    'privacy_tip' = 'shieldHalved'
    'public' = 'globe'
    'query_builder' = 'clock'
    'question_answer' = 'comments'
    'radio_button_checked' = 'circleDot'
    'radio_button_unchecked' = 'regularCircle'
    'rate_review' = 'penToSquare'
    'receipt_long' = 'fileInvoice'
    'receipt' = 'fileInvoice'
    'redeem' = 'gift'
    'remove_circle_outline' = 'regularCircleMinus'
    'remove_red_eye' = 'regularEye'
    'remove' = 'minus'
    'repeat' = 'repeat'
    'report_problem' = 'triangleExclamation'
    'reviews' = 'regularStar'
    'save' = 'regularFloppyDisk'
    'schedule' = 'regularCalendar'
    'school' = 'graduationCap'
    'search' = 'magnifyingGlass'
    'search_off' = 'magnifyingGlass'
    'send' = 'paperPlane'
    'sentiment_dissatisfied' = 'faceFrown'
    'settings' = 'gear'
    'settings_suggest' = 'sliders'
    'share' = 'shareNodes'
    'shield' = 'shield'
    'shopping_cart' = 'cartShopping'
    'star_border' = 'regularStar'
    'star_half' = 'starHalfStroke'
    'star' = 'star'
    'stars' = 'star'
    'straighten' = 'ruler'
    'subscriptions' = 'video'
    'swap_horiz' = 'rightLeft'
    'switch_camera' = 'cameraRotate'
    'timelapse' = 'hourglass'
    'timeline' = 'timeline'
    'timer' = 'clock'
    'title' = 'heading'
    'translate' = 'language'
    'trending_up' = 'arrowTrendUp'
    'unfold_more' = 'anglesUpDown'
    'verified_user' = 'userShield'
    'verified' = 'badgeCheck'
    'videocam' = 'video'
    'videocam_off' = 'videoSlash'
    'view_list' = 'listUl'
    'visibility_off' = 'regularEyeSlash'
    'visibility' = 'regularEye'
    'warning_amber' = 'triangleExclamation'
    'warning' = 'triangleExclamation'
    'wifi_off' = 'wifiSlash'
    'work_history' = 'clockRotateLeft'
    'work_off' = 'briefcaseArrowRight'
    'work_outline' = 'regularBriefcase'
    'work' = 'briefcase'
    'workspace_premium' = 'crown'
    'refresh' = 'rotateRight'
    'call_received' = 'arrowDown'
    'call_made' = 'arrowUp'
}

$faImportLine = "import 'package:font_awesome_flutter/font_awesome_flutter.dart';"

$files = Get-ChildItem -Path lib -Filter *.dart -Recurse
foreach ($file in $files) {
    if ($file.Length -eq 0) { continue }
    $content = Get-Content $file.FullName -Raw
    if ($null -eq $content) { continue }

    # Skip if there are NO Material Icons references in this file at all
    if ($content -notmatch "(?<!FontAwesome)\bIcons\.[a-z]") { continue }

    $Global:safeIconMap = $iconMap
    $modified = $false

    $newContent = [regex]::Replace($content, "(?<!FontAwesome)\bIcons\.([a-zA-Z0-9_]+)\b", {
        param($m)
        $fullName = $m.Groups[1].Value

        # Exact match
        if ($Global:safeIconMap.ContainsKey($fullName)) {
            $script:modified = $true
            return "FontAwesomeIcons.$($Global:safeIconMap[$fullName])"
        }

        # Strip Material suffix and retry
        $baseName = $fullName -replace "(_rounded|_outlined|_sharp|_filled)$", ""
        if ($Global:safeIconMap.ContainsKey($baseName)) {
            $script:modified = $true
            return "FontAwesomeIcons.$($Global:safeIconMap[$baseName])"
        }

        return $m.Value
    })

    if ($modified) {
        # Replace Icon( with FaIcon( where FontAwesomeIcons follows
        $newContent = $newContent -replace "Icon\(FontAwesomeIcons\.", "FaIcon(FontAwesomeIcons."

        # Only inject if not already present
        if ($newContent -notmatch [regex]::Escape($faImportLine)) {
            # Inject ONCE at the first import
            $r = [regex]"import '"
            $newContent = $r.Replace($newContent, "$faImportLine`nimport '", 1)
        }

        Set-Content -Path $file.FullName -Value $newContent -Encoding UTF8
    }
}
