import 'package:flutter/material.dart';

import 'package:nsapp/core/core.dart';

TextTheme lightTextTheme = TextTheme(
  titleSmall: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 14,
    fontWeight: FontWeight.w500,
    color: appBlackColor,
  ),
  titleMedium: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 16,
    fontWeight: FontWeight.w600,
    color: appBlackColor,
  ),
  titleLarge: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 18,
    fontWeight: FontWeight.bold,
    color: appBlackColor,
  ),
  bodyMedium: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: appBlackColor,
  ),
  bodyLarge: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: appBlackColor,
  ),
  bodySmall: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 12,
    fontWeight: FontWeight.w400,
    color: appBlackColor,
  ),
  labelSmall: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 12,
    fontWeight: FontWeight.w400,
    color: appBlackColor,
  ),
  labelMedium: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 14,
    fontWeight: FontWeight.w500,
    color: appBlackColor,
  ),
  labelLarge: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 16,
    fontWeight: FontWeight.bold,
    color: appBlackColor,
  ),
  displaySmall: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: appBlackColor,
  ),
  displayMedium: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: appBlackColor,
  ),
  displayLarge: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 18,
    fontWeight: FontWeight.bold,
    color: appBlackColor,
  ),
  headlineSmall: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 14,
    fontWeight: FontWeight.w400,
    color: appBlackColor,
  ),
  headlineMedium: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: appBlackColor,
  ),
  headlineLarge: TextStyle(fontFamily: 'FuturaPT',
    fontSize: 18,
    fontWeight: FontWeight.bold,
    color: appBlackColor,
  ),
);

